name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Push dist folder to Repo other repo
      - name: Deploy to emndex_front_build
        uses: peaceiris/actions-gh-pages@v3
        with:
            personal_token: ${{ secrets.ACTION_DEPLOY_KEYS }}
            external_repository: manucreative/emndex_front_build
            publish_dir: ./dist
            publish_branch: main
